NAME               = bbftpc
VERSION            = 3.2.0
RELEASE            = 1
PKG_ROOT           = /opt/bbftp

SRC_SUBDIR         = bbftpc

BBFTPC_NAME        = $(NAME)
BBFTPC_VERSION     = $(VERSION)
BBFTPC_PKG_SUFFIX  = tar.gz
BBFTPC_SOURCE_PKG  = $(BBFTPC_NAME)-$(BBFTPC_VERSION).$(BBFTPC_PKG_SUFFIX)
BBFTPC_SOURCE_DIR  = $(BBFTPC_SOURCE_PKG:%.$(BBFTPC_PKG_SUFFIX)=%)

TAR_GZ_PKG         = $(BBFTPC_SOURCE_PKG)
