NAME           = bbcp
VERSION        = 12.08.17
RELEASE        = 0
PKGROOT        = /opt/bbcp

SRC_SUBDIR     = bbcp

SOURCE_NAME    = $(NAME)
SOURCE_SUFFIX  = tgz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

TGZ_PKGS       = $(SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No
