NAME               = bbftpd
VERSION            = 3.2.0
RELEASE            = 1

PKG_ROOT           = /opt/bbftp

SRC_SUBDIR         = bbftpd

BBFTPD_NAME        = $(NAME)
BBFTPD_VERSION     = $(VERSION)
BBFTPD_PKG_SUFFIX  = tgz
BBFTPD_SOURCE_PKG  = $(BBFTPD_NAME)-$(BBFTPD_VERSION).$(BBFTPD_PKG_SUFFIX)
BBFTPD_SOURCE_DIR  = $(BBFTPD_SOURCE_PKG:%.$(BBFTPD_PKG_SUFFIX)=%)

TGZ_PKGS           = $(BBFTPD_SOURCE_PKG)
